image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - wix.vscode-import-cost
    - Vue.volar
    - editorconfig.editorconfig

tasks:
  - name: "Setup workspace"
    init: |
      bash ./scripts/gitpod-init.sh
      gp sync-done setup
  - name: Server
    openMode: tab-after
    command: |
      NODE_ENV="development" yarn run dev
  - name: Server (logs)
    openMode: tab-after
    command: |
      tail -f ./content/logs/logchimp-all.log
  - name: Mail server
    openMode: tab-after
    command: |
      npm install -g maildev
      maildev
  - name: Client
    openMode: tab-after
    command: |
      cd ./packages/theme
      NODE_OPTIONS=--max_old_space_size=4096 LOGCHIMP_THEME_STANDALONE=true yarn dev

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 1080
    onOpen: ignore
  - port: 1025
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
