image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Setup workspace"
    init: |
      bash ./scripts/gitpod-init.sh
      gp sync-done setup
  - name: Server
    openMode: tab-after
    command: |
      gp sync-await setup
      yarn --production=false
      NODE_ENV="development" yarn run dev
  - name: Client
    openMode: tab-after
    command: |
      gp sync-await setup
      git clone https://github.com/logchimp/theme.git
      cd theme
      yarn --production=false
      IS_GITPOD=true yarn run dev

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
  - port: 5432
    onOpen: ignore
