image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Setup workspace"
    init: |
      bash ./scripts/gitpod-init.sh
      gp sync-done setup
  - name: Server
    openMode: tab-after
    command: |
      gp sync-await setup
      NODE_ENV="development" yarn run dev
  - name: Server (logs)
    openMode: tab-after
    command: |
      tail -f ./content/logs/logchimp-all.log
  - name: Mail server
    openMode: tab-after
    command: |
      npm install -g maildev
      maildev
  - name: Client
    openMode: tab-after
    command: |
      gp sync-await setup
      cd theme
      IS_GITPOD=true yarn run dev

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 1080
    onOpen: ignore
  - port: 1025
    onOpen: ignore
