image:
  file: .gitpod.Dockerfile

tasks:
  - name: Init Gitpod
    init: |
      # Install packages
      pnpm Install
      bash ./scripts/gitpod-init.sh 
      gp sync-done setup
  - name: Server
    openMode: tab-after
    command: |
      gp sync-await setup
      pnpm --filter @logchimp/api dev
  - name: Server (logs)
    openMode: tab-after
    command: |
      gp sync-await setup
      tail -f ./content/logs/logchimp-all.log
  - name: Mail server
    openMode: tab-after
    command: |
      npm install -g maildev
      maildev
  - name: Client
    openMode: tab-after
    command: |
      gp sync-await setup
      # export 'APP_SERVER_URL' ENV to file
      echo APP_SERVER_URL=http://localhost:3000 > .env

      pnpm --filter @logchimp/theme dev

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 1080
    onOpen: ignore
  - port: 1025

gitConfig:
  alias.st: status
  alias.co: checkout

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true

vscode:
  extensions:
    - biomejs.biome
    - wix.vscode-import-cost
    - bradlc.vscode-tailwindcss
    - Vue.volar
    - editorconfig.editorconfig
    - ZixuanChen.vitest-explorer
    - syler.sass-indented
    - eamodio.gitlens
