image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      touch ./.wait
      bash ./scripts/gitpod-init.sh
      rm ./.wait
    command: NODE_ENV="development" yarn run server:dev
  - name: Frontend
    init: sleep 1 && while [ -f ./.wait ]; do sleep 1; done
    openMode: tab-after
    command: yarn run frontend:dev --public="$GITPOD_WORKSPACE_URL"

ports:
  - port: 8080
    onOpen: open-preview
