image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Setup workspace"
    init: |
      bash ./scripts/gitpod-init.sh
      gp sync-done setup
  - name: Server
    openMode: tab-after
    command: |
      NODE_ENV="development" pnpm dev
  - name: Server (logs)
    openMode: tab-after
    command: |
      tail -f ./content/logs/logchimp-all.log
  - name: Mail server
    openMode: tab-after
    command: |
      npm install -g maildev
      maildev
  - name: Client
    openMode: tab-after
    command: |
      cd ./packages/theme

      # export 'APP_SERVER_URL' ENV to file
      echo APP_SERVER_URL=http://localhost:3000 > .env

      pnpm dev

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 1080
    onOpen: ignore
  - port: 1025
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - wix.vscode-import-cost
    - Vue.volar
    - editorconfig.editorconfig
    - ZixuanChen.vitest-explorer
