import type { IBoardPrivate } from "@logchimp/types";

export const EXAMPLE_BOARDS_DATA: Array<IBoardPrivate> = [
  // {
  //   boardId: "1",
  //   name: "Feedback",
  //   color: "efefef",
  //   display: true,
  //   post_count: "36",
  //   view_voters: true,
  //   url: "web-application",
  //   createdAt: new Date(Date.now() - 3 * 60 * 1000),
  // },
  {
    boardId: "2",
    name: "Android App",
    color: "abcefa",
    display: true,
    post_count: "97",
    view_voters: true,
    url: "android-app",
    createdAt: new Date(Date.now() - 3 * 60 * 1000),
  },
  {
    boardId: "3",
    name: "Accessibility",
    color: "eecefa",
    display: false,
    post_count: "11",
    view_voters: false,
    url: "accessibility",
    createdAt: new Date(Date.now() - 3 * 60 * 1000),
  },
  {
    boardId: "4",
    name: "iOS App",
    color: "afecee",
    display: true,
    post_count: "53",
    view_voters: true,
    url: "ios-app",
    createdAt: new Date(Date.now() - 3 * 60 * 1000),
  },
  {
    boardId: "5",
    name: "Localisation",
    color: "eecefa",
    display: false,
    post_count: "2",
    view_voters: false,
    url: "localisation",
    createdAt: new Date(Date.now() - 3 * 60 * 1000),
  },
];
