#!/bin/bash

LC_SECRET=$(openssl rand -base64 12)
GH_CS_PUBLIC_THEME_HOST="https://${CODESPACE_NAME}-3000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
GH_CS_PUBLIC_API_HOST="https://${CODESPACE_NAME}-8000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"

# API (Server)
echo "LOGCHIMP_SECRET_KEY=$LC_SECRET" >> packages/server/.env

# Theme
echo "VITE_API_URL=$GH_CS_PUBLIC_THEME_HOST" >> packages/theme/.env
echo "VITE_API_URL_PROXY=$GH_CS_PUBLIC_API_HOST" >> packages/theme/.env
