[files]
extend-exclude = [
  "dist",
  "node_modules",
  "pnpm-lock.yaml",
  "packages/theme/src/locales/{fr,hi}/**/*.json",
  "packages/theme/src/ee/locales/{fr,hi}/**/*.json",
]

[default.extend-words]
# inject-app-env.sh
ba = "ba"