name: "Biome tools"

on:
  workflow_call:

jobs:
  formatter:
    name: Formatter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: biomejs/setup-biome@v2

      - name: Formatter
        run: biome format --max-diagnostics 200 --colors force .

  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: biomejs/setup-biome@v2

      - name: Linter
        run: biome check --max-diagnostics 200 --colors force .
