 version: "3.8"
 services:
   db:
-    image: postgres:12.4
-    ports: ["5000:5432"]
-    environment:
-      POSTGRES_DB: logchimp_db
-      POSTGRES_USER: logchimp_user
-      POSTGRES_PASSWORD: logchimp_password
+    image: postgres:12.4
+    ports:
+      - "${POSTGRES_PORT:-5432}:5432"
+    environment:
+      POSTGRES_DB: ${POSTGRES_DB:-logchimp_dev}
+      POSTGRES_USER: ${POSTGRES_USER:-logchimp}
+      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-logchimp}
+    healthcheck:
+      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
+      interval: 5s
+      timeout: 5s
+      retries: 20
     networks:
-      - logchimp_network
+      - logchimp_network
     volumes:
-      - dbdata:/var/lib/postgresql/data
+      - dbdata:/var/lib/postgresql/data
 networks:
   logchimp_network:
     driver: bridge
 volumes:
-  dbdata: {}
+  dbdata:
+    name: logchimp_dbdata
