name: "Vue tools"

permissions:
  contents: read

on:
  push:
    branches: [ main, master ]
    paths:
      - ".github/workflows/vue-tools.yml"
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - ".github/workflows/vue-tools.yml"
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
    branches-ignore:
      - "**/graphite-base/**"
  workflow_dispatch:

env:
  node-version: 24
  pnpm-version: 10

jobs:
  theme:
    name: Theme / Vue format & lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/submodules
        with:
          token: ${{ secrets.LC_SUBMODULES_TOKEN }}

      - uses: codecarrotlabs/github-actions/.github/actions/node-pnpm@c7e1e7605a3c05a042093219be7020e35b66f494
        with:
          node_version: ${{ env.node-version }}
          pnpm_version: ${{ env.pnpm-version }}

      - name: Prettier
        run: pnpm --filter @logchimp/theme format:check

      - name: ESLint
        run: pnpm --filter @logchimp/theme lint

  email-templates:
    name: Email templates / Vue format & lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/submodules
        with:
          token: ${{ secrets.LC_SUBMODULES_TOKEN }}

      - uses: codecarrotlabs/github-actions/.github/actions/node-pnpm@c7e1e7605a3c05a042093219be7020e35b66f494
        with:
          node_version: ${{ env.node-version }}
          pnpm_version: ${{ env.pnpm-version }}

      - name: Prettier
        run: pnpm --filter @logchimp/email-templates format:check

      - name: ESLint
        run: pnpm --filter @logchimp/email-templates lint
